### ISSUE TITLE
Find classes on ClassInfo

### ISSUE THREAD

**Issue by izziL** [umn-prereq-flowchart/prereq-flowchart#2]
- [x] use classinfo json api
- [ ] extract class prereqs from the text
- [ ] correlate class prereqs to other parsed json objects

**Comment by ritikmishra** [comment]
**my goal for next 10/06**: get `requests` installed into the repo, get classinfo down + JSON parsed into dataclasses, start making an effort at parsing prereqs

**Comment by ritikmishra** [comment]
closed by #5
