### ISSUE TITLE
Find undergraduate majors on OneStop (Catalogs)

### ISSUE THREAD

**Issue by izziL** [umn-prereq-flowchart/prereq-flowchart#3]

**Comment by izziL** [comment]
Identify major requirements:
- minimum number of major credits
- required classes
- required class sets

**Comment by ritikmishra** [comment]
note that some majors are discontinued but still appear on university catalogs -- how do we handle this situation?

**Comment by ritikmishra** [comment]
**your goal for 10/06**: get selenium or pyppeteer (whichever yall choose) to get University Catalogs HTML info Python, and start extracting the `<div>` blocks so that they're ready to be parsed.

**Comment by JosephMcIndoo** [comment]
Was able to extract HTML links to all majors from the main undergrad page. However, trying to go to them through Selenium resulted in stale links. I was able to start from the second link and replicate the error.

**Comment by JosephMcIndoo** [comment]
**Goal for next week:** I'm going to refactor majorinfo.py to make it more organized. In addition, I'll try to output both links and partial class data into JSON. I'll also investigate the errors I got this week.

**Comment by ritikmishra** [comment]
closed by #7
