### ISSUE TITLE
Turn into Graphviz image

### ISSUE THREAD

**Issue by izziL** [umn-prereq-flowchart/prereq-flowchart#4]

**Comment by ritikmishra** [comment]
**your goal for 10/06**: figure out how to use graphviz from python (e.g what libraries we need, what needs to get installed in our computer, etc). ideally, generate some kind of test graph

**Comment by Kanishk-K** [comment]
**Goal for 10/13**: Follow the pre-req flowchart provided by the [https://cse.umn.edu/cs/ug-prerequisite-chart](University) and create a similar graph with the GraphViz setup. Identify stylistic items which could make nice looking graphs.
