### ISSUE TITLE
Configure Graphviz to operate using real generated data.

### ISSUE THREAD

**Issue by Kanishk-K** [umn-prereq-flowchart/prereq-flowchart#9]
Now that we've established a basic method to generate data from a JSON file we now need to account for the generation of graphs from data retrieved by the generous folk over in the data-scrapping team. Let's keep in mind the following ideas which can be modified throughout the course of development.

- [ ] Generate a basic structure from generated data
- [x] Verify that the structure doesn't become overly complicated or begin incessantly overlapping arrows clouding the view
- [ ] Delete test data from the repository
- [x] Account for co-requisites, classes where only one pre-requisite out of a group is needed to be valid. For example, a class may require STAT 3021 or STAT 3022 and MATH 2374 or CSCI 2033. In this case we would need to design a way so that this relationship in modeled. 
- [x] Potentially different background colors and font colors depending on the department a class is taken from (this could be really pretty).

**Comment by ritikmishra** [comment]
also once real data is being used, the test data/files should get removed

**Comment by Kanishk-K** [comment]
I've established a basic JSON structure that we can use to follow the pre-reqs/recommended courses. I will explain my code to the team on 10/20/2022 and confer with the data collection team on the feasibility of the data structure. I'll publish a push to the repo once these concerns have been addressed.

**Comment by ritikmishra** [comment]
closed by #16
